### PR TITLE
Line handler callback & options dictionary

### PR DESCRIPTION
**Pull request by vrischmann**
This PR does multiple things:

* replace the `cwd` argument of `PickFile` with a `options` dictionary
* add the ability to provide a "line handler" in this `options` dictionary which can be provided by the caller to do some processing on the user selection before it's used.
* use the result of the line handler to jump to a line and column if possible

My primary goal was to be able to jump to a line and column which are provided by ripgrep with this command:
```
$ rg --color never --line-number --column selection
README.md
22:25:  available. Fuzzy text selection is done with `fzy` by default: a fast, well
180:1:selection candidates with, combined with any Vim command to run on the output.
197:1:selection for use as a filename (for passing to Vim commands such as `:edit`)
doc/picker.txt
139:21:    with the user's selection as a single argument.
152:50:    escapes spaces and special characters in the selection for use as a
autoload/picker.vim
119:38:    "     invoked against the user's selection, for display in the
171:38:    "     invoked against the user's selection, for display in the
258:38:    "     invoked against the user's selection, for display in the
279:21:    " unadulterated selection, and invoke Picker() with that callback.
```

and I also wanted to be able to see the match because otherwise with multiple match like this it would be almost unusable if only the filename was displayed.

The `line_handler` key in the `options` dict must be the name of a function which takes a single argument which is the user selection, for example:
```
function! PickerRgLineHandler(selection)
    let parts = split(a:selection, ':')

    return {'filename': parts[0], 'line': parts[1], 'column': parts[2]}
endfunction
```

the function must return a dict with at least the `filename` in it, which must not have any formatting. The `line` and `column` are optional.

`s:PickFile`, after jumping to the file, will jump to the line and column if it was provided in the result.

Here is a complete Rg command:
```
command! -nargs=? Rg
    \ call picker#File('rg --color never --line-number --column '.shellescape(<q-args>), "edit", {'line_handler': 'PickerRgLineHandler'})
```

Note: I tried to preserve the current functionality and not break anything but I'm not that familiar with vimscript or vim-picker so it's possible I missed something.

### CODE REVIEW

**Comment by srstevenson** [comment]
Thanks for working on this @vrischmann! When I pass a directory other than the current working directory using this branch (e.g. `:PickerEdit ~/foo/bar`), the file listing is still being done for the current working directory. Can you reproduce that?

**Comment by vrischmann** [comment]
Hm, yes I get the same thing. I'll take a look.

**Comment by vrischmann** [comment]
I completely missed that `cwd` is used in `s:PickerTermStart`, `s:PickerTermopen` and `s:PickerSystemlist`. I believe it's fixed with the commit I just pushed, I tested both `s:PickerTermStart` and `s:PickerSystemlist` but I don't have neovim setup so I can't test `s:PickerTermopen`

**Comment by srstevenson** [comment]
Thanks, that's working for me on Neovim too! We also need to check the callback has an `options` key, as some of the commands such as `PickerHelp` don't take any configuration: 

```diff
diff --git a/autoload/picker.vim b/autoload/picker.vim
index c71ba8b..388d9b9 100644
--- a/autoload/picker.vim
+++ b/autoload/picker.vim
@@ -128,7 +128,9 @@ function! s:PickerTermopen(list_command, vim_command, callback) abort
                 \ }
 
     let l:directory = getcwd()
-    if has_key(a:callback.options, 'cwd') && isdirectory(a:callback.options.cwd)
+    if has_key(a:callback, 'options')
+                \ && has_key(a:callback.options, 'cwd')
+                \ && isdirectory(a:callback.options.cwd)
         let l:callback['cwd'] = a:callback.options.cwd
         let l:directory = a:callback.options.cwd
     endif
```

Can you also some documentation for this in `doc/picker.txt` and `README.txt`? If you want write an initial draft, I'm happy to add an example and flesh it out.

**Comment by vrischmann** [comment]
I added the check, I'll look into adding documentation.

**Comment by vrischmann** [comment]
Ok, I added some documentation. As I'm not a native speaker there may be some grammatical errors, feel free to correct what's wrong.

**Comment by srstevenson** [comment]
@vrischmann Sorry I haven't been able to look at this for a while. Could you rebase this on master?

**Comment by vrischmann** [comment]
Sure

**Comment by vrischmann** [comment]
Everything seems to work as far as I can tell after rebasing

**Review by srstevenson — APPROVED** [review]

**Pull request merged**
