### PR TITLE
Expose some functions directly

### PR DESCRIPTION
**Pull request by abravalheri**
Hi Scott, thank you very much for the awesome extension!

I am proposing in this PR to expose some kind of `picker#File` and `picker#String` functions directly...
Sometimes it is easier to call the functions directly, instead of using picker#Register & picker#Execute.

### CODE REVIEW

**Comment by boxofrox** [comment]
@abravalheri I recommend updating the docs and readme to document these functions.

I'm not a fan of exposing low level functions in the API, since that commits a project to implementation details that are substantially difficult to change later.  I've retained hope that neovim will eventually have a generic named pipe API that will allow vim-picker to write lists of data into the selector program via stdin instead of building a shell command with string parsing (see #24) and suffering errors from escape codes and expansions.

However, this change should provide a fix for #54 by allowing users to dynamically generate the list command.

Deferring to @srstevenson's judgement on the matter.

**Comment by abravalheri** [comment]
@boxofrox thank you very much for your comments and suggestions. Glad to see that the PR accidentally solves an existing issue :P

To be completely fair, the new API introduced (`picker#File` and `picker#String`) expose the exact same amount of information/low lever implementation details as `picker#Register`. They consume 2 of the same arguments, but instead of requiring a `selection_type`, this is informed directly in the name of the function... So, in a way, the APIs of `picker#File` and `picker#String` offers more or less the same level of commitment  to internal implementation as `picker#Register`.

But I agree with you. If you guys don't think the use case is common, it is better to keep the project as lean as possible and avoid future incompatibility.

**Comment by boxofrox** [comment]
> To be completely fair, the new API introduced (picker#File and picker#String) expose the exact same amount of information/low lever implementation details as picker#Register.

Indeed, you are correct.  I withdraw my reservations.  Thanks for updating the docs.  LGTM :+1:

ping @srstevenson

**Review by boxofrox — APPROVED** [review]

**Review by srstevenson — APPROVED** [review]
@abravalheri I've tweaked the documentation a bit but otherwise this is great. Thanks for contributing!

Given the addition of these functions, I'm considering deprecating `picker#Execute()` and `picker#Register()`, as the same result can be achieved with `picker#String()` or `picker#File()` now. This comes at the cost of a bit more scripting on the user's part, but reduces complexity in `vim-picker` (which is something I'm wary of). What do you think @boxofrox?

**Comment by boxofrox** [comment]
> Given the addition of these functions, I'm considering deprecating picker#Execute() and picker#Register()

I wholeheartedly agree.  I wasn't sure how to handle the deprecation smoothly for any users that've adopted those, but you've addressed that simply enough in #59.  Just rip the band-aid off and move along.  I don't see this happening again for a long while, if ever (knock on wood).

I've been facepalming about that feature since I overlooked dynamic generation of shell list commands with the custom user commands and am happy to see them replaced with this simpler and more versatile API.

Thanks for the PR @abravalheri

**Comment by abravalheri** [comment]
Awesome guys! Thanks a lot! Always happy to contribute.

**Pull request merged**
